"""empty message

Revision ID: 3191ffd9c082
Revises: 1bcd6c96ba6f
Create Date: 2023-04-10 19:47:19.660285

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3191ffd9c082'
down_revision = '1bcd6c96ba6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('dt_created', sa.DateTime(), nullable=True))
    op.add_column('article', sa.Column('dt_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'dt_updated')
    op.drop_column('article', 'dt_created')
    # ### end Alembic commands ###
