"""empty message

Revision ID: 3763208ecc9c
Revises: 6ba126adb6b6
Create Date: 2023-04-06 20:46:57.049645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3763208ecc9c'
down_revision = '6ba126adb6b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=80), nullable=False))
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=256), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_staff')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
