"""empty message

Revision ID: 5d67b3cc1cf4
Revises: 3191ffd9c082
Create Date: 2023-04-12 22:18:57.017543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d67b3cc1cf4'
down_revision = '3191ffd9c082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), server_default='', nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('dt_created', sa.DateTime(), nullable=True),
    sa.Column('dt_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('article')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('author_id', sa.INTEGER(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=200), server_default=sa.text("('')"), nullable=False),
    sa.Column('body', sa.TEXT(), server_default=sa.text("('')"), nullable=False),
    sa.Column('dt_created', sa.DATETIME(), nullable=True),
    sa.Column('dt_updated', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('articles')
    # ### end Alembic commands ###
