"""Flask-Bcrypt

Revision ID: 6ba126adb6b6
Revises: 74fddc74bde4
Create Date: 2023-04-06 20:01:11.449486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ba126adb6b6'
down_revision = '74fddc74bde4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_password', sa.LargeBinary(), nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=256), nullable=True))
    op.drop_column('users', '_password')
    # ### end Alembic commands ###
