"""empty message

Revision ID: c69a28c8da8e
Revises: 3763208ecc9c
Create Date: 2023-04-06 20:51:21.284743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69a28c8da8e'
down_revision = '3763208ecc9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=80), nullable=True))
    op.add_column('users', sa.Column('is_staff', sa.Boolean(), nullable=True))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=256), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(length=120),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.drop_column('users', 'is_staff')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
