"""empty message

Revision ID: d8d4617b2d66
Revises: c69a28c8da8e
Create Date: 2023-04-06 20:51:56.879944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d4617b2d66'
down_revision = 'c69a28c8da8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(length=120), server_default=sa.text("('')"), nullable=False))
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=256), nullable=True))
    op.add_column('users', sa.Column('last_name', sa.VARCHAR(length=120), server_default=sa.text("('')"), nullable=False))
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
